export const ADD_SERVICE = 'ADD_SERVICE';
export const REMOVE_SERVICE = 'REMOVE_SERVICE';
export const CHANGE_SERVICE_FIELD = 'CHANGE_SERVICE_FIELD';
//////
export const CHANGE_SERVICE_TO_EDIT = 'CHANGE_SERVICE_TO_EDIT'
export const FILTER_SERVICE_LIST = 'FILTER_SERVICE_LIST'